name = "fclap"
version = "0.1.0"
license = "MIT"
author = ["Christian Selzer"]
maintainer = ["@chselz"]
copyright = "Copyright 2026, Christian Selzer"
keywords = ["arguments", "cli", "parser", "io"]
description = "Command Line Argument Parser in Fortran"

[library]
source-dir = "src"

[build]
auto-tests = false
auto-examples = false

[[example]]
name = "basic"
source-dir = "example"
main = "basic.f90"

[[test]]
name = "tester"
source-dir = "test/unit"
[test.dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive.git"
test-drive.tag = "v0.6.1"
