name = "fclap"
version = "0.1.0"
license = "MIT"
author = ["Christian Selzer"]
maintainer = ["@chselz"]
copyright = "Copyright 2026, Christian Selzer"
keywords = ["io", "cli"]
description = "Command Line Argument Parser in Fortran"

[library]
source-dir = "src"

[build]
auto-tests = false
auto-examples = true

[[test]]
name = "tester"
source-dir = "test/unit"
[test.dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive.git"

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

