# This file is part of fclap.
# SPDX-Identifier: MIT
#
# Licensed under the MIT license; you may not use this file except
# in compliance with the License.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

subdir('utils')

srcs += files(
  'nargs.f90',
  'error/codes.f90',
  'error/entry.f90',
  'error/stack.f90',
  'value/abstract.f90',
  'value/builtin.f90',
  'value/convert.f90',
  'namespace.f90',
  'parse/context.f90',
  'parse/result.f90',
  'actions/abstract.f90',
  'actions/store.f90',
  'actions/boolean.f90',
  'actions/accumulate.f90',
  'actions/control.f90',
  'actions/builtin.f90',
  'validators/abstract.f90',
  'validators/choices.f90',
  'validators/bounds.f90',
  'argument.f90',
  'groups/abstract.f90',
  'groups/helppage.f90',
  'groups/mutex.f90',
  'formatter/model.f90',
  'formatter/abstract.f90',
  'formatter/standard.f90',
  'parse/engine.f90',
  'argparser.f90',
)
